[project]
name = "mints-gui"
version = "0.2.0"
description = "Graphical user interface for the Portland State Aerospace Society Minimal Engine Test Stand"
readme = "README.md"
authors = [
    { name = "William Jeffreys", email = "wjeffreys96@gmail.com" }
]

requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
    "pyside6-stubs>=6.7.3.0",
]

[project.gui-scripts]
mints-gui = "mints_gui.main:main"

[dependency-groups]
lint = [
    "ruff>=0.16.0",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "standard"
